/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sailenawale
 */
public class Dasboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dasboard.class.getName());

    /**
     * Creates new form Dasboard
     */
    public Dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userdashboard = new javax.swing.JLabel();
        hotelid1 = new javax.swing.JLabel();
        hotelname1 = new javax.swing.JLabel();
        Location2 = new javax.swing.JLabel();
        roomstatus2 = new javax.swing.JLabel();
        Ratings2 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        hotelid = new javax.swing.JLabel();
        hotelname = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        roomstatus1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        bookinghistory = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        viewdetails3 = new javax.swing.JButton();
        viewdetails4 = new javax.swing.JButton();
        dashboardimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newmo_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(310, 180));
        jLabel1.setMinimumSize(new java.awt.Dimension(310, 180));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(750, 160, 250, 170);

        userdashboard.setFont(new java.awt.Font("PT Sans", 0, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel1.add(userdashboard);
        userdashboard.setBounds(590, 60, 260, 40);

        hotelid1.setFont(new java.awt.Font("PT Sans", 0, 20)); // NOI18N
        hotelid1.setText("Hotel ID: A1  ");
        jPanel1.add(hotelid1);
        hotelid1.setBounds(420, 340, 170, 30);

        hotelname1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        hotelname1.setText("Hotel Name: Aquaphor  ");
        jPanel1.add(hotelname1);
        hotelname1.setBounds(420, 370, 260, 30);

        Location2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        Location2.setText("Location: Swotha, Patan");
        jPanel1.add(Location2);
        Location2.setBounds(420, 400, 260, 30);

        roomstatus2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        roomstatus2.setText("Room status: Available  ");
        jPanel1.add(roomstatus2);
        roomstatus2.setBounds(420, 430, 244, 30);

        Ratings2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        Ratings2.setText("Rating:       4.5");
        jPanel1.add(Ratings2);
        Ratings2.setBounds(420, 460, 170, 30);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐_1.png"))); // NOI18N
        jPanel1.add(star2);
        star2.setBounds(820, 460, 30, 30);

        hotelid.setFont(new java.awt.Font("PT Sans", 0, 20)); // NOI18N
        hotelid.setText("Hotel ID: B33  ");
        jPanel1.add(hotelid);
        hotelid.setBounds(760, 340, 170, 30);

        hotelname.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        hotelname.setText("Hotel Name: Skyscraper  ");
        jPanel1.add(hotelname);
        hotelname.setBounds(760, 370, 260, 30);

        Location1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        Location1.setText("Location: Jhamsikhel, Lalitpur");
        jPanel1.add(Location1);
        Location1.setBounds(760, 400, 310, 30);

        roomstatus1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        roomstatus1.setText("Room status: Unavailable  ");
        jPanel1.add(roomstatus1);
        roomstatus1.setBounds(760, 430, 271, 30);

        Ratings1.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        Ratings1.setText("Rating:       5");
        jPanel1.add(Ratings1);
        Ratings1.setBounds(760, 460, 170, 30);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐_1.png"))); // NOI18N
        jPanel1.add(star3);
        star3.setBounds(480, 460, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 150, 280, 180);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel1.add(search);
        search.setBounds(920, 60, 40, 40);

        dashboard.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        jPanel1.add(dashboard);
        dashboard.setBounds(70, 150, 150, 32);

        bookinghistory.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        jPanel1.add(bookinghistory);
        bookinghistory.setBounds(70, 190, 220, 40);

        notifications.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        notifications.setForeground(new java.awt.Color(255, 255, 255));
        notifications.setText("Notifications");
        jPanel1.add(notifications);
        notifications.setBounds(70, 240, 180, 30);

        support.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        jPanel1.add(support);
        support.setBounds(70, 280, 150, 30);

        profile.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        jPanel1.add(profile);
        profile.setBounds(70, 320, 150, 32);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        jPanel1.add(dashboardicon);
        dashboardicon.setBounds(20, 150, 42, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jPanel1.add(bookingicon);
        bookingicon.setBounds(20, 185, 50, 40);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        jPanel1.add(notificationsicon);
        notificationsicon.setBounds(20, 230, 50, 40);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        jPanel1.add(supporticon);
        supporticon.setBounds(20, 280, 60, 25);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        jPanel1.add(profileicon);
        profileicon.setBounds(20, 320, 40, 27);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        jPanel1.add(menu);
        menu.setBounds(10, 10, 40, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 600, 130, 90);

        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(90, 660, 90, 17);

        viewdetails3.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails3.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        viewdetails3.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails3.setText("View details");
        viewdetails3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails3ActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetails3);
        viewdetails3.setBounds(760, 510, 240, 50);

        viewdetails4.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails4.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        viewdetails4.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails4.setText("View details");
        viewdetails4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails4ActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetails4);
        viewdetails4.setBounds(420, 510, 240, 50);

        dashboardimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w_2.png"))); // NOI18N
        dashboardimage.setText("jLabel2");
        jPanel1.add(dashboardimage);
        dashboardimage.setBounds(-20, -60, 1280, 850);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetails3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails3ActionPerformed

    private void viewdetails4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dasboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Location2;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel Ratings2;
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JLabel dashboardimage;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel hotelid1;
    private javax.swing.JLabel hotelname;
    private javax.swing.JLabel hotelname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel roomstatus1;
    private javax.swing.JLabel roomstatus2;
    private javax.swing.JLabel search;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JButton viewdetails3;
    private javax.swing.JButton viewdetails4;
    // End of variables declaration//GEN-END:variables
}
