/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class ForgetPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgetPassword.class.getName());

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        forgetpass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ConfirmPass = new javax.swing.JLabel();
        Emailicon = new javax.swing.JLabel();
        Passwordicon = new javax.swing.JLabel();
        Confirmpasswordicon = new javax.swing.JLabel();
        Resetbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        maincolorlabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Email = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        jPanel1.add(email);
        email.setBounds(470, 230, 130, 60);

        forgetpass.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        forgetpass.setForeground(new java.awt.Color(255, 255, 255));
        forgetpass.setText("Forget Password");
        jPanel1.add(forgetpass);
        forgetpass.setBounds(500, 70, 290, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 320, 190, 60);

        ConfirmPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmPass.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPass.setText("Confirmpassword");
        jPanel1.add(ConfirmPass);
        ConfirmPass.setBounds(470, 430, 250, 25);

        Emailicon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Emailicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 3.png")); // NOI18N
        jPanel1.add(Emailicon);
        Emailicon.setBounds(760, 250, 20, 20);

        Passwordicon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Passwordicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 1.png")); // NOI18N
        jPanel1.add(Passwordicon);
        Passwordicon.setBounds(760, 340, 20, 20);

        Confirmpasswordicon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Confirmpasswordicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 1.png")); // NOI18N
        jPanel1.add(Confirmpasswordicon);
        Confirmpasswordicon.setBounds(760, 440, 20, 20);

        Resetbutton.setBackground(new java.awt.Color(185, 12, 46));
        Resetbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Resetbutton.setForeground(new java.awt.Color(255, 255, 255));
        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Resetbutton);
        Resetbutton.setBounds(510, 540, 240, 50);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(470, 270, 310, 20);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(470, 360, 310, 10);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(470, 460, 310, 20);

        maincolorlabel.setBackground(new java.awt.Color(255, 255, 255));
        maincolorlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        maincolorlabel.setForeground(new java.awt.Color(255, 255, 255));
        maincolorlabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Screenshot 2025-12-10 123450.png")); // NOI18N
        jPanel1.add(maincolorlabel);
        maincolorlabel.setBounds(-20, 0, 1280, 720);

        jPasswordField1.setText("Password");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(470, 340, 310, 22);

        jPasswordField2.setText("Confirmpassword");
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(470, 440, 310, 22);

        Email.setColumns(20);
        Email.setRows(5);
        jScrollPane1.setViewportView(Email);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 246, 330, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetbuttonActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgetPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmPass;
    private javax.swing.JLabel Confirmpasswordicon;
    private javax.swing.JTextArea Email;
    private javax.swing.JLabel Emailicon;
    private javax.swing.JLabel Passwordicon;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JLabel email;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel maincolorlabel;
    // End of variables declaration//GEN-END:variables
}
