/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class ForgetPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgetPassword.class.getName());

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        forgetpass = new javax.swing.JLabel();
        Resetbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Email = new javax.swing.JTextArea();
        Emaillabel = new javax.swing.JLabel();
        OTPbutton = new javax.swing.JButton();
        OTP = new javax.swing.JTextField();
        OTPverification = new javax.swing.JButton();
        Newpasswordlabel = new javax.swing.JLabel();
        Newpassword = new javax.swing.JTextField();
        OTPlabel = new javax.swing.JLabel();
        maincolorlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        forgetpass.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        forgetpass.setForeground(new java.awt.Color(241, 150, 174));
        forgetpass.setText("Forgot Password");
        jPanel1.add(forgetpass);
        forgetpass.setBounds(500, 70, 290, 60);

        Resetbutton.setBackground(new java.awt.Color(185, 12, 46));
        Resetbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Resetbutton.setForeground(new java.awt.Color(241, 150, 174));
        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Resetbutton);
        Resetbutton.setBounds(510, 550, 240, 50);

        Email.setColumns(20);
        Email.setRows(5);
        jScrollPane1.setViewportView(Email);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 200, 370, 30);

        Emaillabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Emaillabel.setForeground(new java.awt.Color(255, 255, 255));
        Emaillabel.setText("E-mail");
        jPanel1.add(Emaillabel);
        Emaillabel.setBounds(430, 180, 70, 20);

        OTPbutton.setBackground(new java.awt.Color(185, 12, 46));
        OTPbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OTPbutton.setForeground(new java.awt.Color(255, 255, 255));
        OTPbutton.setText("Send OTP");
        jPanel1.add(OTPbutton);
        OTPbutton.setBounds(570, 240, 100, 27);

        OTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPActionPerformed(evt);
            }
        });
        jPanel1.add(OTP);
        OTP.setBounds(430, 320, 380, 30);

        OTPverification.setBackground(new java.awt.Color(185, 12, 46));
        OTPverification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OTPverification.setForeground(new java.awt.Color(255, 255, 255));
        OTPverification.setText("Verify");
        OTPverification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPverificationActionPerformed(evt);
            }
        });
        jPanel1.add(OTPverification);
        OTPverification.setBounds(570, 360, 110, 27);

        Newpasswordlabel.setBackground(new java.awt.Color(255, 102, 102));
        Newpasswordlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Newpasswordlabel.setForeground(new java.awt.Color(255, 255, 255));
        Newpasswordlabel.setText("New Password");
        jPanel1.add(Newpasswordlabel);
        Newpasswordlabel.setBounds(430, 420, 120, 20);

        Newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Newpassword);
        Newpassword.setBounds(430, 440, 380, 30);

        OTPlabel.setBackground(new java.awt.Color(255, 255, 255));
        OTPlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OTPlabel.setForeground(new java.awt.Color(255, 255, 255));
        OTPlabel.setText("OTP");
        jPanel1.add(OTPlabel);
        OTPlabel.setBounds(430, 300, 70, 20);

        maincolorlabel.setBackground(new java.awt.Color(255, 255, 255));
        maincolorlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        maincolorlabel.setForeground(new java.awt.Color(51, 51, 51));
        maincolorlabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Screenshot 2025-12-10 123450.png")); // NOI18N
        maincolorlabel.setText("Enter the OTP");
        jPanel1.add(maincolorlabel);
        maincolorlabel.setBounds(-20, 10, 1430, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetbuttonActionPerformed

    private void OTPverificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPverificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTPverificationActionPerformed

    private void OTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTPActionPerformed

    private void NewpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgetPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Email;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTextField Newpassword;
    private javax.swing.JLabel Newpasswordlabel;
    private javax.swing.JTextField OTP;
    private javax.swing.JButton OTPbutton;
    private javax.swing.JLabel OTPlabel;
    private javax.swing.JButton OTPverification;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maincolorlabel;
    // End of variables declaration//GEN-END:variables
}
