/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sailenawale
 */
public class NewUserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewUserDashboard.class.getName());

    /**
     * Creates new form NewUserDashboard
     */
    public NewUserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        userdashboard = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        bookinghistory = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        hotelid = new javax.swing.JLabel();
        hotelname = new javax.swing.JLabel();
        roomstatus1 = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        hotelid1 = new javax.swing.JLabel();
        hotelname1 = new javax.swing.JLabel();
        Location2 = new javax.swing.JLabel();
        roomstatus2 = new javax.swing.JLabel();
        Ratings2 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        viewdetails2 = new javax.swing.JButton();
        viewdetails3 = new javax.swing.JButton();
        hotelimage2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-09 at 20.40.10.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1443, 863));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        slogan.setFont(new java.awt.Font("Tamil MN", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel2.add(slogan);
        slogan.setBounds(150, 850, 90, 30);

        userdashboard.setFont(new java.awt.Font("PT Sans", 0, 48)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel2.add(userdashboard);
        userdashboard.setBounds(790, 70, 350, 50);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(search);
        search.setBounds(1230, 70, 40, 40);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        jPanel2.add(menu);
        menu.setBounds(10, 10, 40, 30);

        dashboard.setFont(new java.awt.Font("PT Sans", 0, 30)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        jPanel2.add(dashboard);
        dashboard.setBounds(80, 170, 150, 39);

        bookinghistory.setFont(new java.awt.Font("PT Sans", 0, 30)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        jPanel2.add(bookinghistory);
        bookinghistory.setBounds(80, 230, 220, 39);

        notifications.setFont(new java.awt.Font("PT Sans", 0, 30)); // NOI18N
        notifications.setForeground(new java.awt.Color(255, 255, 255));
        notifications.setText("Notifications");
        jPanel2.add(notifications);
        notifications.setBounds(80, 290, 180, 39);

        support.setFont(new java.awt.Font("PT Sans", 0, 30)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        jPanel2.add(support);
        support.setBounds(80, 350, 150, 39);

        profile.setFont(new java.awt.Font("PT Sans", 0, 30)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        jPanel2.add(profile);
        profile.setBounds(80, 410, 150, 32);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        jPanel2.add(dashboardicon);
        dashboardicon.setBounds(30, 180, 42, 20);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jPanel2.add(bookingicon);
        bookingicon.setBounds(30, 230, 50, 25);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        jPanel2.add(notificationsicon);
        notificationsicon.setBounds(30, 290, 50, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        jPanel2.add(supporticon);
        supporticon.setBounds(30, 350, 60, 25);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        jPanel2.add(profileicon);
        profileicon.setBounds(30, 410, 40, 27);

        hotelid.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        hotelid.setText("Hotel ID: B33  ");
        jPanel2.add(hotelid);
        hotelid.setBounds(1010, 420, 170, 30);

        hotelname.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        hotelname.setText("Hotel Name: Skyscraper  ");
        jPanel2.add(hotelname);
        hotelname.setBounds(1010, 460, 260, 30);

        roomstatus1.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        roomstatus1.setText("Room status: Unavailable  ");
        jPanel2.add(roomstatus1);
        roomstatus1.setBounds(1010, 540, 283, 30);

        Location1.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        Location1.setText("Location: Jhamsikhel, Lalitpur");
        jPanel2.add(Location1);
        Location1.setBounds(1010, 500, 310, 30);

        Ratings1.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        Ratings1.setText("Rating:       5");
        jPanel2.add(Ratings1);
        Ratings1.setBounds(1010, 580, 170, 30);

        hotelid1.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        hotelid1.setText("Hotel ID: A1  ");
        jPanel2.add(hotelid1);
        hotelid1.setBounds(580, 420, 170, 30);

        hotelname1.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        hotelname1.setText("Hotel Name: Aquaphor  ");
        jPanel2.add(hotelname1);
        hotelname1.setBounds(580, 460, 260, 30);

        Location2.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        Location2.setText("Location: Swotha, Patan");
        jPanel2.add(Location2);
        Location2.setBounds(580, 500, 260, 30);

        roomstatus2.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        roomstatus2.setText("Room status: Available  ");
        jPanel2.add(roomstatus2);
        roomstatus2.setBounds(580, 540, 255, 30);

        Ratings2.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        Ratings2.setText("Rating:       4.5");
        jPanel2.add(Ratings2);
        Ratings2.setBounds(580, 580, 170, 30);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐.png"))); // NOI18N
        jPanel2.add(star2);
        star2.setBounds(1090, 580, 40, 30);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐.png"))); // NOI18N
        jPanel2.add(star1);
        star1.setBounds(660, 580, 40, 30);

        viewdetails2.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails2.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        viewdetails2.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails2.setText("View details");
        viewdetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails2ActionPerformed(evt);
            }
        });
        jPanel2.add(viewdetails2);
        viewdetails2.setBounds(1010, 630, 290, 50);

        viewdetails3.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails3.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        viewdetails3.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails3.setText("View details");
        viewdetails3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails3ActionPerformed(evt);
            }
        });
        jPanel2.add(viewdetails3);
        viewdetails3.setBounds(580, 630, 290, 50);

        hotelimage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 4.png"))); // NOI18N
        hotelimage2.setText("jLabel3");
        jPanel2.add(hotelimage2);
        hotelimage2.setBounds(990, 190, 330, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 5.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(520, 180, 370, 240);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-10 at 07.19.50.png"))); // NOI18N
        image.setText("jLabel3");
        jPanel2.add(image);
        image.setBounds(0, 0, 1853, 915);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1440, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails2ActionPerformed

    private void viewdetails3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewUserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Location2;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel Ratings2;
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel hotelid1;
    private javax.swing.JLabel hotelimage2;
    private javax.swing.JLabel hotelname;
    private javax.swing.JLabel hotelname1;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel roomstatus1;
    private javax.swing.JLabel roomstatus2;
    private javax.swing.JLabel search;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JButton viewdetails2;
    private javax.swing.JButton viewdetails3;
    // End of variables declaration//GEN-END:variables
}
