/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sailenawale
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        userdashboard = new javax.swing.JLabel();
        ratings2 = new javax.swing.JLabel();
        hotelid2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hotelid1 = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        roomstatus1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        hotelname2 = new javax.swing.JLabel();
        location2 = new javax.swing.JLabel();
        roomstatus2 = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        viewdetails1 = new javax.swing.JButton();
        viewdetails2 = new javax.swing.JButton();
        bookinghistory = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        userdashboard.setFont(new java.awt.Font("PT Sans", 0, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel3.add(userdashboard);
        userdashboard.setBounds(520, 40, 270, 50);

        ratings2.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        ratings2.setText("Rating:       5  ");
        jPanel3.add(ratings2);
        ratings2.setBounds(700, 390, 170, 30);

        hotelid2.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        hotelid2.setText("Hotel ID: B33  ");
        jPanel3.add(hotelid2);
        hotelid2.setBounds(700, 290, 120, 17);

        jLabel5.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        jLabel5.setText("Hotel ID: A1  ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(400, 290, 170, 30);

        hotelid1.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        hotelid1.setText("Hotel Name: Aquaphor  ");
        jPanel3.add(hotelid1);
        hotelid1.setBounds(400, 320, 170, 30);

        Location1.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        Location1.setText("Location: Swotha, Patan");
        jPanel3.add(Location1);
        Location1.setBounds(400, 350, 170, 30);

        roomstatus1.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        roomstatus1.setText("Room status: Available  ");
        jPanel3.add(roomstatus1);
        roomstatus1.setBounds(400, 380, 130, 30);

        Ratings1.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        Ratings1.setText("Rating:       4.5");
        jPanel3.add(Ratings1);
        Ratings1.setBounds(400, 410, 120, 20);

        hotelname2.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        hotelname2.setText("Hotel Name: Skyscraper  ");
        jPanel3.add(hotelname2);
        hotelname2.setBounds(700, 310, 170, 30);

        location2.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        location2.setText("Location: Jhamsikhel, Lalitpur");
        jPanel3.add(location2);
        location2.setBounds(700, 340, 170, 30);

        roomstatus2.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        roomstatus2.setText("Room status: Unavailable");
        jPanel3.add(roomstatus2);
        roomstatus2.setBounds(700, 370, 170, 20);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jPanel3.add(star1);
        star1.setBounds(440, 410, 20, 20);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        star2.setAlignmentY(0.0F);
        star2.setPreferredSize(new java.awt.Dimension(18, 18));
        jPanel3.add(star2);
        star2.setBounds(740, 400, 50, 10);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        jPanel3.add(menu);
        menu.setBounds(10, 10, 40, 30);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel3.add(search);
        search.setBounds(830, 50, 30, 30);

        slogan.setFont(new java.awt.Font("Tamil MN", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel3.add(slogan);
        slogan.setBounds(90, 580, 90, 30);

        viewdetails1.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails1.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        viewdetails1.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails1.setText("View details");
        viewdetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails1ActionPerformed(evt);
            }
        });
        jPanel3.add(viewdetails1);
        viewdetails1.setBounds(690, 440, 210, 50);

        viewdetails2.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails2.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        viewdetails2.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails2.setText("View details");
        viewdetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails2ActionPerformed(evt);
            }
        });
        jPanel3.add(viewdetails2);
        viewdetails2.setBounds(390, 440, 210, 50);

        bookinghistory.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        jPanel3.add(bookinghistory);
        bookinghistory.setBounds(70, 160, 180, 32);

        notifications.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        notifications.setForeground(new java.awt.Color(255, 255, 255));
        notifications.setText("Notifications");
        jPanel3.add(notifications);
        notifications.setBounds(70, 200, 150, 32);

        profile.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        jPanel3.add(profile);
        profile.setBounds(70, 280, 150, 32);

        dashboard.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        jPanel3.add(dashboard);
        dashboard.setBounds(70, 120, 150, 32);

        support.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        jPanel3.add(support);
        support.setBounds(70, 240, 150, 32);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        jPanel3.add(dashboardicon);
        dashboardicon.setBounds(30, 120, 42, 20);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jPanel3.add(bookingicon);
        bookingicon.setBounds(30, 160, 50, 25);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        jPanel3.add(notificationsicon);
        notificationsicon.setBounds(30, 200, 50, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        jPanel3.add(supporticon);
        supporticon.setBounds(30, 240, 60, 25);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        jPanel3.add(profileicon);
        profileicon.setBounds(30, 280, 60, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-08 at 09.58.47.png"))); // NOI18N
        jPanel3.add(image);
        image.setBounds(0, -90, 1030, 820);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1050, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails1ActionPerformed

    private void viewdetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JLabel hotelid1;
    private javax.swing.JLabel hotelid2;
    private javax.swing.JLabel hotelname2;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel location2;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel ratings2;
    private javax.swing.JLabel roomstatus1;
    private javax.swing.JLabel roomstatus2;
    private javax.swing.JLabel search;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JButton viewdetails1;
    private javax.swing.JButton viewdetails2;
    // End of variables declaration//GEN-END:variables
}
